### ISSUE TITLE
Missing code in server.js from the release.zip file

### ISSUE THREAD

**Issue by jdecaron** [betable/betable-canvas-sdk#1]
I was doing the setup instructions of this readme: https://github.com/betable/betable-canvas-sdk/blob/master/README.md

And I found out that there is a difference between the server.js file from the release.zip file provided in the readme and the one that is provided in the repository. The file from the zip is missing a few things, and more importantly, the canIGamble function.

**Comment by thauber** [comment]
Should be fixed with the Beta Release.
